### ISSUE TITLE
Best Practice for the Template-Location

### ISSUE THREAD

**Issue by spackmat** [mbence/OpenTBSBundle#2]
Hi,

thanks for bundling OpenTBS for Symfony, very useful!

Just a short question: What do you suggest as a path to store the templates in. Your example-code uses no path at all. I put my templates into a `/src/appBundle//Resources/OpenTBSTemplates/` folder, but I am not sure, if this is good practice.

Greets, spackmat

**Comment by mbence** [comment]
That is a pretty good place to put the templates. I'm using the Resources/public/OpenTBSTemplates folder to keep it a little more organized, but I think both are equally ok.

**Comment by spackmat** [comment]
Thanks for your quick answer, so I'll stick with this place.

The path thing could be helpful for other users, so maybe you could say a word or two about that in your readme.

**Comment by mbence** [comment]
Thanks for the suggestion, I will update the readme with that!
