### ISSUE TITLE
OpenTBS generating PHP errors

### ISSUE THREAD

**Issue by sterichards** [mbence/OpenTBSBundle#3]
The following code:

include_once('./src/tbs_class.php');
include_once('./src/tbs_plugin_opentbs.php');

$name = "Stephen";
$age = "30";

$TBS = new clsTinyButStrong;
$TBS->NoErr = true;
$TBS->Plugin(TBS_INSTALL, OPENTBS_PLUGIN);
$TBS->LoadTemplate('./templates/template1.rtf');
$TBS->Show(OPENTBS_DOWNLOAD, "test.rtf");

Generates these errors - http://pastebin.com/SzG0CeX7

**Comment by mbence** [comment]
These are some small notices in the OpenTBS plugin, please report them in the original repo: https://github.com/Skrol29/opentbs

**Comment by mbence** [comment]
In the meantime you could try to turn off notices in error reporting for the time you use TBS.
http://php.net/manual/en/function.error-reporting.php
```
$originalSetting = error_reporting();
error_reporting(E_ALL & ~E_NOTICE);

... do your thing ...

error_reporting($originalSetting);
```
