### ISSUE TITLE
Problem detecting variables

### ISSUE THREAD

**Issue by joeljv91** [mbence/OpenTBSBundle#5]
Hii, i'm using your bundle and i'm having some issues, some variables are not detected with mergeField and mergeBlock. Have you seen this problem before?

**Comment by mbence** [comment]
Hi @joeljv91, as this is only a bundle around the openTBS code, you should try the original repo: https://github.com/Skrol29/opentbs or the forums: http://www.tinybutstrong.com/forum.php

**Comment by joeljv91** [comment]
Thx, i'm going to try in the original repo.
