### ISSUE TITLE
With symfony 3...

### ISSUE THREAD

**Issue by ikerib** [mbence/OpenTBSBundle#6]
[InvalidArgumentException]
  Could not find package mbence/opentbs-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by mbence** [comment]
Thanks @ikerib! Just updated the bundle with the latest versions, and tagged it to fix this issue.
Please check if this solves the problem!

**Comment by ikerib** [comment]
Oks. I´ll try it now. I was able to make it work with
"mbence/opentbs-bundle": "dev-master as 1.0.x-dev"

But I´m going to update it now.

**Comment by ikerib** [comment]
It´s working. Thanks!
