### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by lena773** [mbence/OpenTBSBundle#7]
Hi,

I am trying to implement the OpenTBSBundle in my project. Locally i work with xampp on Windows, but our server runs on Ubuntu. Locally i installed all. and  now the bundle and the Action in the controller work perfectly. But on Server  i become an error 500. In console there are no mistakes, the folder on Server has rights r-x. And i have no ideas where can be the mistake.

Could you please help me?

Thank you in advance,
respectfully yourth,
Lena

**Comment by mbence** [comment]
Hi Lena,

this looks like some configuration problem on your server, that your server admin should try to fix. 500 means some kind of fatal error, missing files, or wrong php version. Can you check the logs for the error message?

**Comment by lena773** [comment]
Thank you for the answer. The problem is that  in the log file there are any mistakes too. I am working wih symfony. During the installation of bundle were any problems.

and the problem is in this line:
$TBS = $this->container->get('opentbs');

In this line i am becoming the error 500

**Comment by mbence** [comment]
That means, that you probably don't have a $this->container member in your object. If you are in a controller, then you can simply use **$this->get('opentbs')**. 
In a service you should use DI to inject the required dependencies: https://symfony.com/doc/current/service_container.html#referencing-injecting-services

**Comment by lena773** [comment]
Thank you for the answer. I have found in the logs file from appache 

[Tue Sep 27 14:41:34.548362 2016] [fcgid:warn] [pid 26272] (104)Connection reset by peer: [client 192.168.2.18:50031] mod_fcgid: error reading data from FastCGI server, referer:
[Tue Sep 27 14:41:34.548401 2016] [core:error] [pid 26272] [client 192.168.2.18:50031] End of script output before headers: app.php, referer:.

**Comment by mbence** [comment]
Dear Lena, this problem has nothing to do with the bundle. I'm sorry, but I can't help you here with general programming issues.
